# Generated by Django 4.2.16 on 2025-03-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
