# Generated by Django 4.2.16 on 2025-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
