# Generated by Django 4.2.16 on 2025-03-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_schedule_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
