# Generated by Django 4.2.16 on 2025-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_plan_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
