# Generated by Django 4.2.16 on 2025-03-12 21:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_plan_link_alter_schedule_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='attachement',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='trip_files'),
        ),
    ]
