# Generated by Django 4.2.16 on 2025-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_schedule_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='link',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='link',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
